# Generated by Django 5.2.15 on 2026-08-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0150_part_maximum_stock'),
        ('stock', '0123_remove_stockitem_review_needed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChassisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('manufacturer', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('form_factor', models.CharField(blank=True, choices=[('TINY', 'Tiny'), ('USFF', 'USFF'), ('SFF', 'SFF'), ('TOWER', 'Tower'), ('LAPTOP', 'Laptop')], max_length=16, null=True)),
                ('ambiguous', models.BooleanField(default=False)),
                ('ram_slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('supports_optical', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=128)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refurb_chassis_model', to='part.part')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ambiguous', True), ('form_factor__isnull', False), _connector='OR'), name='refurb_chassismodel_ambiguous_or_resolved')],
            },
        ),
        migrations.CreateModel(
            name='ChassisState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('AWAITING_AUDIT', 'Awaiting audit'), ('REVIEW_QUEUE', 'Review queue'), ('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('SHIPPED', 'Shipped'), ('RETURNED', 'Returned'), ('SCRAP', 'Scrap')], default='RECEIVED', max_length=16)),
                ('form_factor', models.CharField(blank=True, choices=[('TINY', 'Tiny'), ('USFF', 'USFF'), ('SFF', 'SFF'), ('TOWER', 'Tower'), ('LAPTOP', 'Laptop')], max_length=16, null=True)),
                ('form_factor_source', models.CharField(blank=True, max_length=32)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_os', models.BooleanField(default=False)),
                ('os_licence', models.CharField(blank=True, max_length=128)),
                ('field_modified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refurb_chassis_state', to='stock.stockitem')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'form_factor'], name='refurb_chas_status_a909e5_idx')],
            },
        ),
    ]
